from __future__ import annotations

from typing import Any

Lab = dict[str, Any]


def _lab(lab_id: str, title: str, track: str, ops: list[dict], checks: list[dict], **kw) -> Lab:
    return {
        "id": lab_id,
        "title": title,
        "track": track,
        "ops": ops,
        "checks": checks,
        **kw,
    }


FIO_MODULE = """&НаКлиенте
Процедура ФамилияПриИзменении(Элемент)
  Объект.Наименование=Объект.Фамилия + " " + Объект.Имя + " " + Объект.Отчество;
КонецПроцедуры
&НаКлиенте
Процедура ИмяПриИзменении(Элемент)
  Объект.Наименование=Объект.Фамилия + " " + Объект.Имя + " " + Объект.Отчество;
КонецПроцедуры
&НаКлиенте
Процедура ОтчествоПриИзменении(Элемент)
  Объект.Наименование=Объект.Фамилия + " " + Объект.Имя + " " + Объект.Отчество;
КонецПроцедуры
"""

SUM_MODULE = """&НаКлиенте
Процедура СоставПриОкончанииРедактирования(Элемент, НоваяСтрока, ОтменаРедактирования)
  Объект.Сумма=Объект.Состав.Итог("Сумма");
КонецПроцедуры
"""

RETURN_MODULE = """Процедура ОбработкаПроведения(Отказ, Режим)
 Движения.ДвижениеДенежныхСредств.Записывать = Истина;
 Движение = Движения.ДвижениеДенежныхСредств.Добавить();
 Движение.ВидДвижения = ?(ВозвратФизическомуЛицу,ВидДвиженияНакопления.Расход, ВидДвиженияНакопления.Приход);
 Движение.Период = Дата;
 Движение.ВидСтатьиДДС = СтатьяДДС.ВидСтатьи;
 Движение.СтатьяДДС = СтатьяДДС;
 Движение.Сумма = Сумма;
 Движения.Взаиморасчеты.Записывать = Истина;
 Движение = Движения.Взаиморасчеты.Добавить();
 Движение.ВидДвижения = ?(ВозвратФизическомуЛицу,ВидДвиженияНакопления.Приход, ВидДвиженияНакопления.Расход);
 Движение.Период = Дата;
 Движение.ФизическоеЛицо = ФизическоеЛицо;
 Движение.Сумма = Сумма;
КонецПроцедуры
"""


LABS: list[Lab] = [
    _lab(
        "00_uchebnaya",
        "Конфигурация Учебная — подсистемы, справочники, документы",
        "uchebnaya",
        ops=[
            {"op": "set_config_name", "name": "Учебная"},
            {"op": "create_subsystem", "name": "Бухгалтерия"},
            {"op": "create_subsystem", "name": "Кадры"},
            {"op": "create_subsystem", "name": "Склад"},
            {"op": "create_catalog", "name": "Банки", "description_length": 100, "subsystems": ["Бухгалтерия"]},
            {"op": "fill_catalog", "catalog": "Банки", "items": [
                {"description": "Сбербанк"},
                {"description": "ВТБ"},
                {"description": "Альфа-Банк"},
            ]},
            {"op": "create_catalog", "name": "Контрагенты", "hierarchical": True,
             "hierarchy_type": "HierarchyFoldersAndItems", "subsystems": ["Бухгалтерия", "Склад"]},
            {"op": "fill_catalog", "catalog": "Контрагенты", "items": [
                {"description": "Покупатели", "is_folder": True},
                {"description": "Поставщики", "is_folder": True},
                {"description": "ООО Ромашка", "parent": "Покупатели"},
                {"description": "ИП Иванов", "parent": "Покупатели"},
                {"description": "ООО Василёк", "parent": "Поставщики"},
            ]},
            {"op": "create_catalog", "name": "ФизическиеЛица", "subsystems": ["Кадры"]},
            {"op": "create_tabular_section", "object": "Catalog.ФизическиеЛица", "name": "ПаспортныеДанные"},
            {"op": "add_attribute", "object": "Catalog.ФизическиеЛица.TabularSection.ПаспортныеДанные",
             "name": "СерияИНомер", "type": "String:20"},
            {"op": "add_attribute", "object": "Catalog.ФизическиеЛица.TabularSection.ПаспортныеДанные",
             "name": "КемВыдан", "type": "String:0"},
            {"op": "add_attribute", "object": "Catalog.ФизическиеЛица.TabularSection.ПаспортныеДанные",
             "name": "ДатаВыдачи", "type": "Date"},
            {"op": "add_attribute", "object": "Catalog.ФизическиеЛица.TabularSection.ПаспортныеДанные",
             "name": "Адрес", "type": "String:0"},
            {"op": "fill_catalog", "catalog": "ФизическиеЛица", "items": [
                {"description": "Петров П.П.", "tabular": {"ПаспортныеДанные": [
                    {"СерияИНомер": "4510 123456", "КемВыдан": "ОВД", "ДатаВыдачи": "2015-05-01", "Адрес": "Москва"}]}},
                {"description": "Сидорова А.А.", "tabular": {"ПаспортныеДанные": [
                    {"СерияИНомер": "4511 654321", "КемВыдан": "МФЦ", "ДатаВыдачи": "2018-03-12", "Адрес": "Москва"}]}},
                {"description": "Козлов И.И.", "tabular": {"ПаспортныеДанные": [
                    {"СерияИНомер": "4512 111222", "КемВыдан": "УФМС", "ДатаВыдачи": "2020-01-20", "Адрес": "Химки"}]}},
            ]},
            {"op": "create_catalog", "name": "ЕдиницыИзмерения", "subsystems": ["Склад", "Бухгалтерия"]},
            {"op": "add_predefined", "catalog": "ЕдиницыИзмерения", "name": "кг", "description": "кг"},
            {"op": "add_predefined", "catalog": "ЕдиницыИзмерения", "name": "м", "description": "м"},
            {"op": "add_predefined", "catalog": "ЕдиницыИзмерения", "name": "шт", "description": "шт"},
            {"op": "fill_catalog", "catalog": "ЕдиницыИзмерения", "items": [{"description": "литр"}]},
            {"op": "create_document", "name": "ПриемНаРаботу", "subsystems": ["Кадры"]},
            {"op": "add_attribute", "object": "Document.ПриемНаРаботу", "name": "ФИО", "type": "String:0"},
            {"op": "add_attribute", "object": "Document.ПриемНаРаботу", "name": "Должность", "type": "String:80"},
            {"op": "add_attribute", "object": "Document.ПриемНаРаботу", "name": "Оклад", "type": "Number:10,0"},
            {"op": "create_tabular_section", "object": "Document.ПриемНаРаботу", "name": "ЛичныеДанные"},
            {"op": "add_attribute", "object": "Document.ПриемНаРаботу.TabularSection.ЛичныеДанные",
             "name": "Паспорт", "type": "String:0"},
            {"op": "add_attribute", "object": "Document.ПриемНаРаботу.TabularSection.ЛичныеДанные",
             "name": "Адрес", "type": "String:100"},
            {"op": "add_attribute", "object": "Document.ПриемНаРаботу.TabularSection.ЛичныеДанные",
             "name": "СемейноеПоложение", "type": "Boolean"},
            {"op": "fill_document", "document": "ПриемНаРаботу", "count": 3},
            {"op": "create_document", "name": "ПриходныйКассовыйОрдер", "subsystems": ["Бухгалтерия"]},
            {"op": "add_attribute", "object": "Document.ПриходныйКассовыйОрдер",
             "name": "ФизическоеИлиЮридическоеЛицо", "type": "String:50"},
            {"op": "add_attribute", "object": "Document.ПриходныйКассовыйОрдер",
             "name": "НазваниеОрганизации", "type": "String:0"},
            {"op": "create_tabular_section", "object": "Document.ПриходныйКассовыйОрдер", "name": "Финансы"},
            {"op": "add_attribute", "object": "Document.ПриходныйКассовыйОрдер.TabularSection.Финансы",
             "name": "Валюта", "type": "String:30"},
            {"op": "add_attribute", "object": "Document.ПриходныйКассовыйОрдер.TabularSection.Финансы",
             "name": "Сумма", "type": "Number:10,2"},
            {"op": "fill_document", "document": "ПриходныйКассовыйОрдер", "count": 3},
            {"op": "copy_document", "from": "ПриходныйКассовыйОрдер", "to": "РасходныйКассовыйОрдер",
             "subsystems": ["Бухгалтерия"]},
            {"op": "fill_document", "document": "РасходныйКассовыйОрдер", "count": 3},
        ],
        checks=[
            {"check": "config_name", "equals": "Учебная"},
            {"check": "has_subsystem", "name": "Бухгалтерия"},
            {"check": "has_subsystem", "name": "Кадры"},
            {"check": "has_subsystem", "name": "Склад"},
            {"check": "has_catalog", "name": "Банки", "description_length": 100},
            {"check": "catalog_in_subsystem", "catalog": "Банки", "subsystem": "Бухгалтерия"},
            {"check": "catalog_count", "catalog": "Банки", "min": 3},
            {"check": "has_catalog", "name": "Контрагенты", "hierarchical": True},
            {"check": "folder_exists", "catalog": "Контрагенты", "name": "Покупатели"},
            {"check": "folder_exists", "catalog": "Контрагенты", "name": "Поставщики"},
            {"check": "has_tabular_section", "object": "Catalog.ФизическиеЛица", "name": "ПаспортныеДанные"},
            {"check": "has_attribute", "object": "Catalog.ФизическиеЛица.TabularSection.ПаспортныеДанные",
             "name": "СерияИНомер", "type": "String(20)"},
            {"check": "catalog_count", "catalog": "ФизическиеЛица", "min": 3},
            {"check": "has_predefined", "catalog": "ЕдиницыИзмерения", "names": ["кг", "м", "шт"]},
            {"check": "catalog_count", "catalog": "ЕдиницыИзмерения", "min": 1},
            {"check": "has_document", "name": "ПриемНаРаботу"},
            {"check": "has_tabular_section", "object": "Document.ПриемНаРаботу", "name": "ЛичныеДанные"},
            {"check": "document_count", "document": "ПриемНаРаботу", "min": 3},
            {"check": "has_document", "name": "ПриходныйКассовыйОрдер"},
            {"check": "has_document", "name": "РасходныйКассовыйОрдер"},
            {"check": "document_count", "document": "ПриходныйКассовыйОрдер", "min": 3},
            {"check": "document_count", "document": "РасходныйКассовыйОрдер", "min": 3},
        ],
    ),
    _lab(
        "10_ms_lab1",
        "Мои события №1 — подсистемы и справочники",
        "moi_sobytiya",
        ops=[
            {"op": "set_config_name", "name": "МоиСобытия", "synonym": "Мои события"},
            {"op": "create_subsystem", "name": "События", "picture": True},
            {"op": "create_subsystem", "name": "Финансы", "picture": True},
            {"op": "create_subsystem", "name": "Контакты", "picture": True},
            {"op": "set_subsystem_order", "names": ["Контакты", "События", "Финансы"]},
            {"op": "create_catalog", "name": "ВидыКонтактов", "description_length": 50, "subsystems": ["Контакты"]},
            {"op": "fill_catalog", "catalog": "ВидыКонтактов", "items": [
                {"description": x} for x in ["E-mail", "Skype", "Сайт", "Адрес", "Телефон"]
            ]},
            {"op": "create_catalog", "name": "СтатусыДрузей", "description_length": 150, "subsystems": ["Контакты"]},
            {"op": "fill_catalog", "catalog": "СтатусыДрузей", "items": [
                {"description": x} for x in ["Друг", "Знакомая", "Знакомый", "Подруга", "Семья"]
            ]},
            {"op": "create_enum", "name": "Пол", "values": ["Мужской", "Женский"], "subsystems": ["Контакты"]},
            {"op": "create_catalog", "name": "Друзья", "description_length": 150, "subsystems": ["Контакты"]},
            {"op": "add_attribute", "object": "Catalog.Друзья", "name": "Пол", "type": "EnumRef.Пол"},
            {"op": "add_attribute", "object": "Catalog.Друзья", "name": "Статус", "type": "CatalogRef.СтатусыДрузей"},
            {"op": "add_attribute", "object": "Catalog.Друзья", "name": "Комментарий", "type": "String:0"},
            {"op": "create_tabular_section", "object": "Catalog.Друзья", "name": "Контакты"},
            {"op": "add_attribute", "object": "Catalog.Друзья.TabularSection.Контакты",
             "name": "Контакт", "type": "CatalogRef.ВидыКонтактов"},
            {"op": "add_attribute", "object": "Catalog.Друзья.TabularSection.Контакты",
             "name": "Значение", "type": "String:200"},
            {"op": "fill_catalog", "catalog": "Друзья", "items": [
                {"description": "Иванов Иван", "attrs": {"Пол": "Мужской", "Статус": "Друг"},
                 "tabular": {"Контакты": [{"Контакт": "Телефон", "Значение": "+7 900 000-00-01"}]}},
                {"description": "Петрова Анна", "attrs": {"Пол": "Женский", "Статус": "Подруга"},
                 "tabular": {"Контакты": [{"Контакт": "E-mail", "Значение": "anna@example.com"}]}},
                {"description": "Сидоров Олег", "attrs": {"Пол": "Мужской", "Статус": "Знакомый"},
                 "tabular": {"Контакты": [{"Контакт": "Skype", "Значение": "oleg.s"}]}},
            ]},
            {"op": "create_catalog", "name": "СтатусыСобытий", "description_length": 150, "subsystems": ["События"]},
            {"op": "fill_catalog", "catalog": "СтатусыСобытий", "items": [
                {"description": x} for x in ["Встреча", "Отдых", "Спорт", "Учеба"]
            ]},
            {"op": "create_catalog", "name": "События", "description_length": 150, "subsystems": ["События"]},
            {"op": "add_attribute", "object": "Catalog.События", "name": "ДатаНачала", "type": "DateTime"},
            {"op": "add_attribute", "object": "Catalog.События", "name": "ДатаОкончания", "type": "DateTime"},
            {"op": "add_attribute", "object": "Catalog.События", "name": "Статус", "type": "CatalogRef.СтатусыСобытий"},
            {"op": "add_attribute", "object": "Catalog.События", "name": "Описание", "type": "String:0"},
            {"op": "create_tabular_section", "object": "Catalog.События", "name": "Участники"},
            {"op": "add_attribute", "object": "Catalog.События.TabularSection.Участники",
             "name": "Друг", "type": "CatalogRef.Друзья"},
            {"op": "fill_catalog", "catalog": "События", "items": [
                {"description": "День рождения", "attrs": {"Статус": "Встреча", "Описание": "дома"},
                 "tabular": {"Участники": [{"Друг": "Иванов Иван"}]}},
                {"description": "Тренировка", "attrs": {"Статус": "Спорт"}},
                {"description": "Сессия", "attrs": {"Статус": "Учеба"}},
            ]},
        ],
        checks=[
            {"check": "config_name", "equals": "МоиСобытия"},
            {"check": "has_subsystem", "name": "События", "picture": True},
            {"check": "has_subsystem", "name": "Финансы", "picture": True},
            {"check": "has_subsystem", "name": "Контакты", "picture": True},
            {"check": "subsystem_order", "names": ["Контакты", "События", "Финансы"]},
            {"check": "has_catalog", "name": "ВидыКонтактов", "description_length": 50},
            {"check": "catalog_count", "catalog": "ВидыКонтактов", "min": 5},
            {"check": "has_catalog", "name": "СтатусыДрузей", "description_length": 150},
            {"check": "has_enum", "name": "Пол", "values": ["Мужской", "Женский"]},
            {"check": "has_attribute", "object": "Catalog.Друзья", "name": "Пол"},
            {"check": "has_tabular_section", "object": "Catalog.Друзья", "name": "Контакты"},
            {"check": "catalog_count", "catalog": "Друзья", "min": 3},
            {"check": "has_catalog", "name": "СтатусыСобытий"},
            {"check": "has_attribute", "object": "Catalog.События", "name": "ДатаНачала"},
            {"check": "has_tabular_section", "object": "Catalog.События", "name": "Участники"},
            {"check": "catalog_count", "catalog": "События", "min": 3},
        ],
    ),
    _lab(
        "11_ms_lab2",
        "Мои события №2 — регистр и кассовые документы",
        "moi_sobytiya",
        ops=[
            {"op": "create_register", "name": "ФинансовыеОперации", "subsystems": ["Финансы"]},
            {"op": "add_dimension", "register": "ФинансовыеОперации", "name": "Событие", "type": "CatalogRef.События"},
            {"op": "add_dimension", "register": "ФинансовыеОперации", "name": "Друг", "type": "CatalogRef.Друзья"},
            {"op": "add_resource", "register": "ФинансовыеОперации", "name": "Сумма", "type": "Number:10,2"},
            {"op": "create_document", "name": "ПоступлениеДенег", "subsystems": ["Финансы"]},
            {"op": "create_tabular_section", "object": "Document.ПоступлениеДенег", "name": "Поступления"},
            {"op": "add_attribute", "object": "Document.ПоступлениеДенег.TabularSection.Поступления",
             "name": "Событие", "type": "CatalogRef.События"},
            {"op": "add_attribute", "object": "Document.ПоступлениеДенег.TabularSection.Поступления",
             "name": "Друг", "type": "CatalogRef.Друзья"},
            {"op": "add_attribute", "object": "Document.ПоступлениеДенег.TabularSection.Поступления",
             "name": "Сумма", "type": "Number:10,2,nn"},
            {"op": "bind_register", "document": "ПоступлениеДенег", "register": "ФинансовыеОперации",
             "movement": "Receipt"},
            {"op": "fill_document", "document": "ПоступлениеДенег", "items": [
                {"number": str(i), "posted": True,
                 "tabular": {"Поступления": [{"Событие": "День рождения", "Друг": "Иванов Иван", "Сумма": 1000 * i}]}}
                for i in range(1, 6)
            ]},
            {"op": "copy_document", "from": "ПоступлениеДенег", "to": "РасходДенег",
             "subsystems": ["Финансы"], "tabular_rename": ["Поступления", "Затраты"]},
            {"op": "bind_register", "document": "РасходДенег", "register": "ФинансовыеОперации",
             "movement": "Expense"},
            {"op": "fill_document", "document": "РасходДенег", "items": [
                {"number": str(i), "posted": True,
                 "tabular": {"Затраты": [{"Событие": "Тренировка", "Друг": "Сидоров Олег", "Сумма": 200 * i}]}}
                for i in range(1, 6)
            ]},
        ],
        checks=[
            {"check": "has_register", "name": "ФинансовыеОперации"},
            {"check": "register_dimension", "register": "ФинансовыеОперации", "name": "Событие"},
            {"check": "register_dimension", "register": "ФинансовыеОперации", "name": "Друг"},
            {"check": "register_resource", "register": "ФинансовыеОперации", "name": "Сумма"},
            {"check": "has_document", "name": "ПоступлениеДенег"},
            {"check": "document_moves", "document": "ПоступлениеДенег", "register": "ФинансовыеОперации",
             "movement": "Receipt"},
            {"check": "document_count", "document": "ПоступлениеДенег", "min": 5},
            {"check": "has_document", "name": "РасходДенег"},
            {"check": "has_tabular_section", "object": "Document.РасходДенег", "name": "Затраты"},
            {"check": "document_moves", "document": "РасходДенег", "register": "ФинансовыеОперации",
             "movement": "Expense"},
            {"check": "document_count", "document": "РасходДенег", "min": 5},
            {"check": "register_movements", "register": "ФинансовыеОперации", "min_receipt": 5, "min_expense": 5},
        ],
    ),
    _lab(
        "12_ms_lab3",
        "Мои события №3 — отчёты Затраты и СколькоДенег",
        "moi_sobytiya",
        ops=[
            {"op": "create_report", "name": "Затраты", "subsystems": ["Финансы"],
             "query_table": "ФинансовыеОперации.ОстаткиИОбороты",
             "fields": ["Друг", "Событие", "СуммаОборот", "СуммаПриход", "СуммаРасход"],
             "resources": ["СуммаКонечныйОстаток", "СуммаНачальныйОстаток", "СуммаОборот", "СуммаПриход", "СуммаРасход"],
             "group_by": ["Друг", "Событие"], "user_params": ["НачалоПериода", "КонецПериода"]},
            {"op": "run_report", "report": "Затраты"},
            {"op": "create_report", "name": "СколькоДенег", "subsystems": ["Финансы"],
             "query_table": "ФинансовыеОперацииОстатки",
             "fields": ["Период", "СуммаОстаток"], "resources": ["СуммаОстаток"],
             "user_params": ["Период"]},
            {"op": "run_report", "report": "СколькоДенег"},
        ],
        checks=[
            {"check": "has_report", "name": "Затраты"},
            {"check": "has_report", "name": "СколькоДенег"},
            {"check": "report_run", "report": "Затраты"},
            {"check": "report_run", "report": "СколькоДенег"},
        ],
    ),
    _lab(
        "13_ms_lab4",
        "Мои события №4 — графики и вариант отчёта",
        "moi_sobytiya",
        ops=[
            {"op": "create_report", "name": "ГрафикПоДням", "subsystems": ["Финансы"],
             "query_table": "ФинансовыеОперацииОстаткиИОбороты",
             "fields": ["Период", "СуммаКонечныйОстаток"], "resources": ["СуммаКонечныйОстаток"],
             "chart": True, "chart_type": "График",
             "user_params": ["НачалоПериода", "КонецПериода"]},
            {"op": "run_report", "report": "ГрафикПоДням"},
            {"op": "add_report_variant", "report": "Затраты", "name": "График 3D"},
            {"op": "run_report", "report": "Затраты", "variant": "График 3D"},
        ],
        checks=[
            {"check": "has_report", "name": "ГрафикПоДням"},
            {"check": "report_chart", "report": "ГрафикПоДням"},
            {"check": "report_run", "report": "ГрафикПоДням"},
            {"check": "report_variant", "report": "Затраты", "name": "График 3D"},
            {"check": "report_run", "report": "Затраты", "variant": "График 3D"},
        ],
    ),
    _lab(
        "14_ms_lab5",
        "Мои события №5 — формы, синонимы, рабочий стол",
        "moi_sobytiya",
        ops=[
            {"op": "create_form", "object": "AccumulationRegister.ФинансовыеОперации",
             "name": "ФормаСписка", "kind": "list",
             "deleted_fields": ["Регистратор", "НомерСтроки"],
             "extra": {"width": 10, "sum_align": "left", "period_title": "Дата"}},
            {"op": "create_form", "object": "Catalog.Друзья", "name": "ФормаСписка", "kind": "list"},
            {"op": "create_form", "object": "Report.СколькоДенег", "name": "ФормаОтчета", "kind": "report"},
            {"op": "set_synonym", "object": "Catalog.Друзья.StandardAttribute.Description", "synonym": "ФИО"},
            {"op": "create_form", "object": "Catalog.Друзья", "name": "ФормаЭлемента", "kind": "object"},
            {"op": "set_synonym", "object": "Catalog.События.StandardAttribute.Description", "synonym": "Название"},
            {"op": "set_synonym", "object": "Catalog.События.TabularSection.Участники.Друг", "synonym": "Участник"},
            {"op": "create_form", "object": "Catalog.События", "name": "ФормаЭлемента", "kind": "object"},
            {"op": "set_object_presentation", "catalog": "ВидыКонтактов", "presentation": "Вид контактов"},
            {"op": "set_object_presentation", "catalog": "СтатусыДрузей", "presentation": "Статус друзей"},
            {"op": "set_object_presentation", "catalog": "Друзья", "presentation": "Друг"},
            {"op": "set_object_presentation", "catalog": "СтатусыСобытий", "presentation": "Статус событий"},
            {"op": "set_object_presentation", "catalog": "События", "presentation": "Событие"},
            {"op": "set_quick_choice", "catalog": "ВидыКонтактов"},
            {"op": "set_quick_choice", "catalog": "СтатусыДрузей"},
            {"op": "set_quick_choice", "catalog": "СтатусыСобытий"},
            {"op": "set_desktop", "layout": {
                "template": "TwoColumnsVariableWidth",
                "left": ["AccumulationRegister.ФинансовыеОперации", "Report.СколькоДенег"],
                "right": ["Catalog.Друзья"],
            }},
        ],
        checks=[
            {"check": "has_form", "object": "AccumulationRegister.ФинансовыеОперации", "name": "ФормаСписка"},
            {"check": "has_form", "object": "Catalog.Друзья", "name": "ФормаСписка"},
            {"check": "has_form", "object": "Catalog.Друзья", "name": "ФормаЭлемента"},
            {"check": "has_form", "object": "Catalog.События", "name": "ФормаЭлемента"},
            {"check": "synonym", "object": "Catalog.Друзья.Description", "equals": "ФИО"},
            {"check": "object_presentation", "catalog": "Друзья", "equals": "Друг"},
            {"check": "object_presentation", "catalog": "События", "equals": "Событие"},
            {"check": "quick_choice", "catalog": "ВидыКонтактов"},
            {"check": "quick_choice", "catalog": "СтатусыДрузей"},
            {"check": "quick_choice", "catalog": "СтатусыСобытий"},
            {"check": "desktop_set"},
        ],
    ),
    _lab(
        "20_ds_lab1",
        "Учет ДС №1 — справочники и авто-ФИО",
        "uchet_ds",
        ops=[
            {"op": "set_config_name", "name": "УчетЛичныхДенежныхСредств",
             "synonym": "Учет личных денежных средств"},
            {"op": "create_subsystem", "name": "Справочники"},
            {"op": "create_subsystem", "name": "Документы"},
            {"op": "create_subsystem", "name": "Регистры"},
            {"op": "create_subsystem", "name": "ДоходыИРасходы", "parent": "Документы"},
            {"op": "create_subsystem", "name": "ДеньгиВДолг", "parent": "Документы"},
            {"op": "create_subsystem", "name": "Отчет", "parent": "Документы"},
            {"op": "create_catalog", "name": "ВидыСтатейДоходовИРасходов", "description_length": 100,
             "subsystems": ["Справочники"]},
            {"op": "create_catalog", "name": "СтатьиДоходовИРасходов", "hierarchical": True,
             "description_length": 25, "subsystems": ["Справочники"]},
            {"op": "add_attribute", "object": "Catalog.СтатьиДоходовИРасходов",
             "name": "ВидСтатьи", "type": "CatalogRef.ВидыСтатейДоходовИРасходов"},
            {"op": "create_catalog", "name": "ФизическиеЛица", "subsystems": ["Справочники"]},
            {"op": "add_attribute", "object": "Catalog.ФизическиеЛица", "name": "Фамилия", "type": "String:33"},
            {"op": "add_attribute", "object": "Catalog.ФизическиеЛица", "name": "Имя", "type": "String:33"},
            {"op": "add_attribute", "object": "Catalog.ФизическиеЛица", "name": "Отчество", "type": "String:33"},
            {"op": "create_form", "object": "Catalog.ФизическиеЛица", "name": "ФормаЭлемента",
             "kind": "object", "module": FIO_MODULE},
            {"op": "fill_catalog", "catalog": "ВидыСтатейДоходовИРасходов", "items": [
                {"description": x} for x in [
                    "Ввод начальных остатков", "Деньги, полученные в подарок", "Подарки на 23 февраля",
                    "Подарки на 8 марта", "Подарки на День рождения", "Подарки на Новый год",
                    "Покупки", "Поступление денежных средств", "Расходы на еду",
                    "Расходы на кафе, бары", "Расходы на спорт", "Расходы на транспорт",
                    "Расчеты по взятым в долг деньгам", "Расчеты по отданным в долг деньгам",
                ]
            ]},
            {"op": "fill_catalog", "catalog": "СтатьиДоходовИРасходов", "items": [
                {"description": "Кафе, бары", "is_folder": True},
                {"description": "Подарки", "is_folder": True},
                {"description": "Поездки на транспорте", "is_folder": True},
                {"description": "Стипендия", "attrs": {"ВидСтатьи": "Поступление денежных средств"}},
                {"description": "Обед в столовой", "parent": "Кафе, бары",
                 "attrs": {"ВидСтатьи": "Расходы на кафе, бары"}},
                {"description": "Автобус", "parent": "Поездки на транспорте",
                 "attrs": {"ВидСтатьи": "Расходы на транспорт"}},
            ]},
            {"op": "fill_catalog", "catalog": "ФизическиеЛица", "items": [
                {"description": "Иванов Иван Иванович", "attrs": {"Фамилия": "Иванов", "Имя": "Иван", "Отчество": "Иванович"}},
                {"description": "Петрова Анна Сергеевна", "attrs": {"Фамилия": "Петрова", "Имя": "Анна", "Отчество": "Сергеевна"}},
            ]},
        ],
        checks=[
            {"check": "config_name", "equals": "УчетЛичныхДенежныхСредств"},
            {"check": "has_subsystem", "name": "Справочники"},
            {"check": "has_subsystem", "name": "ДоходыИРасходы", "parent": "Документы"},
            {"check": "has_subsystem", "name": "ДеньгиВДолг", "parent": "Документы"},
            {"check": "has_catalog", "name": "ВидыСтатейДоходовИРасходов", "description_length": 100},
            {"check": "has_catalog", "name": "СтатьиДоходовИРасходов", "hierarchical": True},
            {"check": "has_attribute", "object": "Catalog.СтатьиДоходовИРасходов", "name": "ВидСтатьи"},
            {"check": "has_attribute", "object": "Catalog.ФизическиеЛица", "name": "Фамилия", "type": "String(33)"},
            {"check": "module_contains", "catalog": "ФизическиеЛица",
             "needle": "Объект.Наименование=Объект.Фамилия"},
            {"check": "catalog_count", "catalog": "ВидыСтатейДоходовИРасходов", "min": 14},
            {"check": "folder_exists", "catalog": "СтатьиДоходовИРасходов", "name": "Кафе, бары"},
            {"check": "catalog_count", "catalog": "ФизическиеЛица", "min": 2},
        ],
    ),
    _lab(
        "21_ds_lab2",
        "Учет ДС №2 — документы",
        "uchet_ds",
        ops=[
            {"op": "create_document", "name": "ПоступлениеДенежныхСредств", "subsystems": ["ДоходыИРасходы"]},
            {"op": "add_attribute", "object": "Document.ПоступлениеДенежныхСредств",
             "name": "СтатьяДДС", "type": "CatalogRef.СтатьиДоходовИРасходов"},
            {"op": "add_attribute", "object": "Document.ПоступлениеДенежныхСредств",
             "name": "Сумма", "type": "Number:15,2"},
            {"op": "add_attribute", "object": "Document.ПоступлениеДенежныхСредств",
             "name": "Содержание", "type": "String:100", "multiline": True},
            {"op": "create_form", "object": "Document.ПоступлениеДенежныхСредств", "name": "ФормаДокумента"},
            {"op": "fill_document", "document": "ПоступлениеДенежныхСредств", "count": 6},
            {"op": "create_document", "name": "РасходДенежныхСредств", "subsystems": ["ДоходыИРасходы"]},
            {"op": "add_attribute", "object": "Document.РасходДенежныхСредств",
             "name": "Сумма", "type": "Number:15,2"},
            {"op": "create_tabular_section", "object": "Document.РасходДенежныхСредств", "name": "Состав"},
            {"op": "add_attribute", "object": "Document.РасходДенежныхСредств.TabularSection.Состав",
             "name": "СтатьяДДС", "type": "CatalogRef.СтатьиДоходовИРасходов"},
            {"op": "add_attribute", "object": "Document.РасходДенежныхСредств.TabularSection.Состав",
             "name": "Сумма", "type": "Number:15,2"},
            {"op": "add_attribute", "object": "Document.РасходДенежныхСредств.TabularSection.Состав",
             "name": "Содержание", "type": "String:100"},
            {"op": "create_form", "object": "Document.РасходДенежныхСредств", "name": "ФормаДокумента",
             "module": SUM_MODULE},
            {"op": "write_form_module", "object": "Document.РасходДенежныхСредств", "code": SUM_MODULE},
            {"op": "fill_document", "document": "РасходДенежныхСредств", "count": 5},
            {"op": "create_document", "name": "ВыдачаДенегВДолг", "subsystems": ["ДеньгиВДолг"]},
            {"op": "add_attribute", "object": "Document.ВыдачаДенегВДолг",
             "name": "ФизическоеЛицо", "type": "CatalogRef.ФизическиеЛица"},
            {"op": "add_attribute", "object": "Document.ВыдачаДенегВДолг", "name": "Сумма", "type": "Number:15,2"},
            {"op": "add_attribute", "object": "Document.ВыдачаДенегВДолг", "name": "Содержание", "type": "String:100"},
            {"op": "add_attribute", "object": "Document.ВыдачаДенегВДолг", "name": "ДатаВозврата", "type": "Date"},
            {"op": "add_attribute", "object": "Document.ВыдачаДенегВДолг",
             "name": "СтатьяДДС", "type": "CatalogRef.СтатьиДоходовИРасходов"},
            {"op": "create_form", "object": "Document.ВыдачаДенегВДолг", "name": "ФормаДокумента"},
            {"op": "fill_document", "document": "ВыдачаДенегВДолг", "count": 3},
            {"op": "create_document", "name": "ПолучениеДенегВДолг", "subsystems": ["ДеньгиВДолг"]},
            {"op": "add_attribute", "object": "Document.ПолучениеДенегВДолг",
             "name": "ФизическоеЛицо", "type": "CatalogRef.ФизическиеЛица"},
            {"op": "add_attribute", "object": "Document.ПолучениеДенегВДолг", "name": "Сумма", "type": "Number:15,2"},
            {"op": "add_attribute", "object": "Document.ПолучениеДенегВДолг", "name": "Содержание", "type": "String:100"},
            {"op": "add_attribute", "object": "Document.ПолучениеДенегВДолг", "name": "ДатаВозврата", "type": "Date"},
            {"op": "add_attribute", "object": "Document.ПолучениеДенегВДолг",
             "name": "СтатьяДДС", "type": "CatalogRef.СтатьиДоходовИРасходов"},
            {"op": "create_form", "object": "Document.ПолучениеДенегВДолг", "name": "ФормаДокумента"},
            {"op": "fill_document", "document": "ПолучениеДенегВДолг", "items": [{"number": "1", "posted": True}]},
            {"op": "create_document", "name": "ВозвратДолга", "subsystems": ["ДеньгиВДолг"]},
            {"op": "add_attribute", "object": "Document.ВозвратДолга",
             "name": "ФизическоеЛицо", "type": "CatalogRef.ФизическиеЛица"},
            {"op": "add_attribute", "object": "Document.ВозвратДолга", "name": "ВозвратФизическомуЛицу", "type": "Boolean"},
            {"op": "add_attribute", "object": "Document.ВозвратДолга", "name": "Сумма", "type": "Number:15,2"},
            {"op": "add_attribute", "object": "Document.ВозвратДолга", "name": "Комментарий", "type": "String:100"},
            {"op": "add_attribute", "object": "Document.ВозвратДолга",
             "name": "СтатьяДДС", "type": "CatalogRef.СтатьиДоходовИРасходов"},
            {"op": "create_form", "object": "Document.ВозвратДолга", "name": "ФормаДокумента"},
            {"op": "fill_document", "document": "ВозвратДолга", "count": 1},
        ],
        checks=[
            {"check": "has_document", "name": "ПоступлениеДенежныхСредств"},
            {"check": "document_count", "document": "ПоступлениеДенежныхСредств", "min": 6},
            {"check": "has_tabular_section", "object": "Document.РасходДенежныхСредств", "name": "Состав"},
            {"check": "module_contains", "document": "РасходДенежныхСредств",
             "needle": 'Объект.Состав.Итог("Сумма")'},
            {"check": "document_count", "document": "РасходДенежныхСредств", "min": 5},
            {"check": "has_document", "name": "ВыдачаДенегВДолг"},
            {"check": "document_count", "document": "ВыдачаДенегВДолг", "min": 3},
            {"check": "has_document", "name": "ПолучениеДенегВДолг"},
            {"check": "posted_count", "document": "ПолучениеДенегВДолг", "min": 1},
            {"check": "has_document", "name": "ВозвратДолга"},
            {"check": "has_attribute", "object": "Document.ВозвратДолга", "name": "ВозвратФизическомуЛицу"},
        ],
    ),
    _lab(
        "22_ds_lab3",
        "Учет ДС №3 — регистры и движения ПДС/РДС/Выдача",
        "uchet_ds",
        ops=[
            {"op": "create_register", "name": "ДвижениеДенежныхСредств", "subsystems": ["Регистры"]},
            {"op": "add_dimension", "register": "ДвижениеДенежныхСредств",
             "name": "ВидСтатьиДДС", "type": "CatalogRef.ВидыСтатейДоходовИРасходов"},
            {"op": "add_dimension", "register": "ДвижениеДенежныхСредств",
             "name": "СтатьяДДС", "type": "CatalogRef.СтатьиДоходовИРасходов"},
            {"op": "add_resource", "register": "ДвижениеДенежныхСредств", "name": "Сумма", "type": "Number:15,2"},
            {"op": "create_register", "name": "Взаиморасчеты", "subsystems": ["Регистры"]},
            {"op": "add_dimension", "register": "Взаиморасчеты",
             "name": "ФизическоеЛицо", "type": "CatalogRef.ФизическиеЛица"},
            {"op": "add_resource", "register": "Взаиморасчеты", "name": "Сумма", "type": "Number:15,2"},
            {"op": "bind_register", "document": "ПоступлениеДенежныхСредств",
             "register": "ДвижениеДенежныхСредств", "movement": "Receipt"},
            {"op": "bind_register", "document": "РасходДенежныхСредств",
             "register": "ДвижениеДенежныхСредств", "movement": "Expense"},
            {"op": "bind_register", "document": "ВыдачаДенегВДолг",
             "register": "ДвижениеДенежныхСредств", "movement": "Expense"},
            {"op": "bind_register", "document": "ВыдачаДенегВДолг",
             "register": "Взаиморасчеты", "movement": "Receipt"},
        ],
        checks=[
            {"check": "has_register", "name": "ДвижениеДенежныхСредств"},
            {"check": "register_dimension", "register": "ДвижениеДенежныхСредств", "name": "СтатьяДДС"},
            {"check": "has_register", "name": "Взаиморасчеты"},
            {"check": "document_moves", "document": "ПоступлениеДенежныхСредств",
             "register": "ДвижениеДенежныхСредств", "movement": "Receipt"},
            {"check": "document_moves", "document": "РасходДенежныхСредств",
             "register": "ДвижениеДенежныхСредств", "movement": "Expense"},
            {"check": "document_moves", "document": "ВыдачаДенегВДолг",
             "register": "Взаиморасчеты", "movement": "Receipt"},
        ],
    ),
    _lab(
        "23_ds_lab4",
        "Учет ДС №4 — ПолучениеВДолг, Возврат, перепроведение",
        "uchet_ds",
        ops=[
            {"op": "bind_register", "document": "ПолучениеДенегВДолг",
             "register": "ДвижениеДенежныхСредств", "movement": "Receipt"},
            {"op": "bind_register", "document": "ПолучениеДенегВДолг",
             "register": "Взаиморасчеты", "movement": "Expense"},
            {"op": "bind_register", "document": "ВозвратДолга",
             "register": "ДвижениеДенежныхСредств", "movement": "Receipt"},
            {"op": "bind_register", "document": "ВозвратДолга",
             "register": "Взаиморасчеты", "movement": "Expense"},
            {"op": "write_object_module", "document": "ВозвратДолга", "code": RETURN_MODULE},
            {"op": "post_all", "document": "ПоступлениеДенежныхСредств"},
            {"op": "post_all", "document": "РасходДенежныхСредств"},
            {"op": "post_all", "document": "ВыдачаДенегВДолг"},
            {"op": "post_all", "document": "ПолучениеДенегВДолг"},
            {"op": "post_all", "document": "ВозвратДолга"},
        ],
        checks=[
            {"check": "document_moves", "document": "ПолучениеДенегВДолг",
             "register": "ДвижениеДенежныхСредств", "movement": "Receipt"},
            {"check": "document_moves", "document": "ВозвратДолга",
             "register": "Взаиморасчеты", "movement": "Expense"},
            {"check": "module_contains", "document": "ВозвратДолга",
             "needle": "?(ВозвратФизическомуЛицу,ВидДвиженияНакопления.Расход"},
            {"check": "posted_count", "document": "ПоступлениеДенежныхСредств", "min": 6},
            {"check": "posted_count", "document": "РасходДенежныхСредств", "min": 5},
            {"check": "register_movements", "register": "ДвижениеДенежныхСредств", "min": 1},
            {"check": "register_movements", "register": "Взаиморасчеты", "min": 1},
        ],
    ),
    _lab(
        "24_ds_lab5",
        "Учет ДС №5 — отчёт Анализ движения ДС",
        "uchet_ds",
        ops=[
            {"op": "create_report", "name": "АнализДвиженияДенежныхСредств", "subsystems": ["Отчет"],
             "query_table": "ДвижениеДенежныхСредств.ОстаткиИОбороты",
             "fields": ["Период", "ВидСтатьиДДС", "СтатьяДДС", "СуммаНачальныйОстаток",
                        "СуммаПриход", "СуммаРасход", "СуммаКонечныйОстаток"],
             "resources": ["СуммаНачальныйОстаток", "СуммаПриход", "СуммаРасход", "СуммаКонечныйОстаток"],
             "user_params": ["НачалоПериода", "КонецПериода", "Отбор"]},
            {"op": "run_report", "report": "АнализДвиженияДенежныхСредств"},
            {"op": "run_report", "report": "АнализДвиженияДенежныхСредств",
             "filter": {"ВидСтатьиДДС": "Расходы на транспорт"}},
        ],
        checks=[
            {"check": "has_report", "name": "АнализДвиженияДенежныхСредств"},
            {"check": "report_run", "report": "АнализДвиженияДенежныхСредств"},
        ],
    ),
    _lab(
        "25_ds_lab6",
        "Учет ДС №6 — взаиморасчёты и график ДДС",
        "uchet_ds",
        ops=[
            {"op": "create_report", "name": "СостояниеВзаиморасчетов", "subsystems": ["Отчет"],
             "query_table": "ВзаиморасчетыОстаткиИОбороты",
             "fields": ["ФизическоеЛицо", "СуммаНачальныйОстаток", "СуммаПриход",
                        "СуммаРасход", "СуммаКонечныйОстаток"],
             "resources": ["СуммаНачальныйОстаток", "СуммаПриход", "СуммаРасход", "СуммаКонечныйОстаток"],
             "group_by": ["ФизическоеЛицо"],
             "user_params": ["НачалоПериода", "КонецПериода"]},
            {"op": "run_report", "report": "СостояниеВзаиморасчетов"},
            {"op": "create_report", "name": "ДвижениеДенежныхСредств", "subsystems": ["Отчет"],
             "query_table": "ДвижениеДенежныхСредствОстаткиИОбороты",
             "fields": ["Период", "СуммаКонечныйОстаток"], "resources": ["СуммаКонечныйОстаток"],
             "chart": True, "chart_type": "График",
             "user_params": ["НачалоПериода", "КонецПериода", "Отбор"]},
            {"op": "run_report", "report": "ДвижениеДенежныхСредств"},
            {"op": "run_report", "report": "ДвижениеДенежныхСредств", "filter": {"СтатьяДДС": "Стипендия"}},
        ],
        checks=[
            {"check": "has_report", "name": "СостояниеВзаиморасчетов"},
            {"check": "has_report", "name": "ДвижениеДенежныхСредств"},
            {"check": "report_chart", "report": "ДвижениеДенежныхСредств"},
            {"check": "report_run", "report": "СостояниеВзаиморасчетов"},
            {"check": "report_run", "report": "ДвижениеДенежныхСредств"},
        ],
    ),
]


BY_ID = {lab["id"]: lab for lab in LABS}
TRACKS = {
    "uchebnaya": ["00_uchebnaya"],
    "moi_sobytiya": ["10_ms_lab1", "11_ms_lab2", "12_ms_lab3", "13_ms_lab4", "14_ms_lab5"],
    "uchet_ds": ["20_ds_lab1", "21_ds_lab2", "22_ds_lab3", "23_ds_lab4", "24_ds_lab5", "25_ds_lab6"],
}
